### ISSUE TITLE
#define-d macro not used in demo

### ISSUE THREAD

**Issue by duffo64** [Seeed-Studio/Gesture_PAJ7620#1]
#define GES_REACTION_TIME		500

**Comment by Jack1314** [comment]
Yes, you can ignore it. GES_REACTION_TIME is used in the paj7620_15gestures.ino, its effect is the same to GES_ENTRY_TIME.
Thanks!

**Comment by Jack1314** [comment]
Yes, you can ignore it. GES_REACTION_TIME is used in the paj7620_15gestures.ino, its effect is the same to GES_ENTRY_TIME.
Thanks!
