### ISSUE TITLE
Transmission error with Intel Arduino and Grove Base Shield v2.

### ISSUE THREAD

**Issue by gavan1** [Seeed-Studio/Gesture_PAJ7620#3]
Unable to init.

https://forum.seeedstudio.com/viewtopic.php?f=17&t=8017#p27289

**Comment by Pillar1989** [comment]
![DeepinScreenshot_select-area_20190731134607](https://user-images.githubusercontent.com/4081906/62186786-f4351b00-b399-11e9-8e11-3af3d55ea04d.png)

I took a casual test and found no problem
